Checkout button
oystparis/oyst-1click-magento pull request #335
Opened 2018-04-18 10:06 UTC by rus-daniel

2018-04-18 13:18 UTC, mehdichaouch approved these changes

2018-04-18 13:33 UTC, mehdichaouch requested changes

2018-04-18 13:33 UTC, mehdichaouch commented on app/design/frontend/base/default/layout/oyst_oneclick.xml
> +            <action method="addItem"><type>skin_js</type><name>js/oyst/checkout/onepage/oneclick.js</name></action>
Why you didn't add ```ifconfig="oyst/oneclick/enable"```to the ```skin_js``` also?

2018-04-18 13:33 UTC, mehdichaouch commented on skin/frontend/base/default/js/oyst/checkout/onepage/oneclick.js
> +{
move the brace to the previous line

2018-04-18 13:33 UTC, mehdichaouch commented on skin/frontend/base/default/js/oyst/checkout/onepage/oneclick.js
> +
useless breakline.

2018-04-20 15:00 UTC, mehdichaouch approved these changes

2018-05-29 07:50 UTC, mbouchotoyst approved these changes

2018-05-31 12:53 UTC, mehdichaouch commented on skin/frontend/base/default/js/oyst/checkout/onepage/oneclick.js
> +            var el = document.evaluate(xpathExpression, document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;
Arf :/
Do you have a ninja plan B?

2018-06-01 09:11 UTC, StefBrito approved these changes
Good pour moi

2018-06-01 09:54 UTC, merged