Manage oyst order status for redirect checkout cart page (#300)
oystparis/oyst-1click-magento pull request #374
Opened 2018-05-18 12:06 UTC by mehdichaouch

2018-05-18 13:49 UTC, mbouchotoyst commented on app/code/community/Oyst/OneClick/controllers/Checkout/CartController.php
> +            $currentTime = new DateTime();
Checker ici que le l'heure renvoyée par le order / Oyst est bien sur le timezone UTC sinon la comparaison sera fausse.

2018-05-18 13:54 UTC, mbouchotoyst requested changes

2018-05-18 13:54 UTC, mbouchotoyst commented on app/code/community/Oyst/OneClick/controllers/Checkout/CartController.php
> +    private function isOystOrderStatusValid($oystOrderId)
Cette méthode a du sens d'être positionnée dans un model et non pas dans le controller car elle contient de la logique métier, de plus elle peut être appelée à d'autres endroits y compris en script php console. De plus il faudrait sortir le set du $this->data = Mage::getBaseUrl()...., ce n'est pas la responsabilité d'une méthode GET de faire cela. cette méthode doit juste renvoyer true ou false.

A l'endroit ou elle est appellée on devrait avoir 
if(Mage::getModel()->isOystOrderStatusValid()) {
  $this->data = Mage::getBaseUrl()+success_suffix
} else {
  $this->data = Mage::getBaseUrl()+error_suffix
  return;
}

2018-05-18 15:36 UTC, mehdichaouch commented on app/code/community/Oyst/OneClick/controllers/Checkout/CartController.php
> +            $currentTime = new DateTime();
Comment je procède ?

2018-05-18 15:41 UTC, mehdichaouch commented on app/code/community/Oyst/OneClick/controllers/Checkout/CartController.php
> +            $currentTime = new DateTime();
Trouvé :)

2018-05-22 07:44 UTC, mbouchotoyst approved these changes

2018-06-04 09:29 UTC, StefBrito approved these changes
Good pour moi ^^

2018-06-04 09:54 UTC, mbouchotoyst approved these changes

2018-06-04 09:54 UTC, merged