Prefill form (#408)
oystparis/oyst-1click-magento pull request #417
Opened 2018-06-25 11:01 UTC by mehdichaouch

2018-06-25 12:39 UTC, mbouchotoyst requested changes

2018-06-25 12:39 UTC, mbouchotoyst commented on app/code/community/Oyst/OneClick/Model/ApiWrapper/Type/OneClick.php
> +    private function getUser()
Méthode à mettre en visibilité protected pour l extensiblité

2018-06-27 08:26 UTC, mbouchotoyst approved these changes

2018-06-27 15:45 UTC, StefBrito approved these changes
Good pour moi

2018-06-27 15:49 UTC, merged