Compliance with catalog rules and sync quote items in cart estimate (#410)
oystparis/oyst-1click-magento pull request #418
Opened 2018-06-25 12:29 UTC by mbouchotoyst

2018-06-25 13:13 UTC, mehdichaouch requested changes

2018-06-25 13:13 UTC, mehdichaouch commented on app/code/community/Oyst/OneClick/Model/Catalog.php
> +            if($item->getParentItemId()) {
run CSFIX add the end of your changes plz ;-)

2018-06-25 13:13 UTC, mehdichaouch commented on app/code/community/Oyst/OneClick/Model/Catalog.php
> +    protected function getCartItems($apiData, $magentoQuoteBuilder, $oneClickOrderCartEstimate)
It seams that ```$apiData``` is not used.
Why you don't use reference of ```$magentoQuoteBuilder``` and ```$oneClickOrderCartEstimate```?

2018-06-25 13:13 UTC, mehdichaouch commented on app/code/community/Oyst/OneClick/Model/Catalog.php
> +                $reference = $item->getProductId().';'.$item->getId();
```else``` is not mandatory.
You can move ```$reference = $item->getProductId().';'.$item->getId();``` this above ```if (in_array($item->getProductType(), array('configurable'))) {```

2018-06-25 13:13 UTC, mehdichaouch commented on app/code/community/Oyst/OneClick/Model/Catalog.php
> +        foreach ($magentoQuoteBuilder->getQuote()->getAllItems() as $item) {
Rename ```$item``` as ```$quoteItem```

2018-06-25 13:13 UTC, mehdichaouch commented on app/code/community/Oyst/OneClick/Model/Catalog.php
> +            if (in_array($item->getProductType(), array('configurable'))) {
change for:
```$item->getProduct()->isConfigurable())```

2018-06-25 13:13 UTC, mehdichaouch commented on app/code/community/Oyst/OneClick/Model/Catalog.php
> +                $reference, $oystPriceIncludingTaxes, $item->getQty()
Each params per line or all in one line.

2018-06-25 13:13 UTC, mehdichaouch commented on app/code/community/Oyst/OneClick/Model/Magento/Quote.php
> +            Mae::getSingleton('customer/session')->setCustomer($customer);
```Mae```??? -_-'

2018-06-25 13:13 UTC, mehdichaouch commented on app/locale/en_US/Oyst_OneClick.csv
> +"Oyst has recognized you as a customer, so you benefit a promotion on this product.","Oyst has recognized you as a customer, so you benefit a promotion on this product."
Add new line add the end of file.

2018-06-25 13:13 UTC, mehdichaouch commented on app/locale/fr_FR/Oyst_OneClick.csv
> +"Oyst has recognized you as a customer, so you benefit a promotion on this product.","Oyst vous a identifié en tant que client, vous bénéficiez d'une promotion sur ce produit."
Add new line add the end of file.

2018-06-27 16:20 UTC, mehdichaouch approved these changes

2018-06-28 14:55 UTC, StefBrito approved these changes
Good pour moi

2018-06-28 15:20 UTC, merged